server:
  port: 8081
  servlet:
    context-path: /ovapi/
  tomcat:
      basedir:
         /tmp/tomcat/rtadmin

spring:
  profiles:
    active: dev  #激活环境
  servlet:
     multipart:
        max-file-size: 30MB
        max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null


